SELECT * FROM dba_data_files;

CREATE TABLESPACE bcycle64K
    datafile '/u01/app/oracle/odata/WOLCOTTDB/bcycle64K.dbf'
    SIZE 193K AUTOEXTEND ON
    EXTENT MANAGEMENT LOCAL UNIFORM SIZE 64K
    SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE bcycle128K
    datafile '/u01/app/oracle/odata/WOLCOTTDB/bcycle128K.dbf'
    SIZE 257K AUTOEXTEND ON
    EXTENT MANAGEMENT LOCAL UNIFORM SIZE 128K
    SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE bcycle32M
    datafile '/u01/app/oracle/odata/WOLCOTTDB/bcycle32M.dbf'
    SIZE 32832K AUTOEXTEND ON
    EXTENT MANAGEMENT LOCAL UNIFORM SIZE 32M
    SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE bcycle64M
    datafile '/u01/app/oracle/odata/WOLCOTTDB/bcycle64M.dbf'
    SIZE 65536K AUTOEXTEND ON
    EXTENT MANAGEMENT LOCAL UNIFORM SIZE 64M
    SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE bcycle8192M
    datafile '/u01/app/oracle/odata/WOLCOTTDB/bcycle8192M.dbf'
    SIZE 8404992K AUTOEXTEND ON
    EXTENT MANAGEMENT LOCAL UNIFORM SIZE 8192M
    SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE bcycle16384M
    datafile '/u01/app/oracle/odata/WOLCOTTDB/bcycle16384M.dbf'
    SIZE 16809984K AUTOEXTEND ON
    EXTENT MANAGEMENT LOCAL UNIFORM SIZE 16384M
    SEGMENT SPACE MANAGEMENT AUTO;


ALTER USER XOXOGOSSIP QUOTA 100M ON bcycle64K;

ALTER USER XOXOGOSSIP QUOTA 100M ON bcycle128K;

ALTER USER XOXOGOSSIP QUOTA 100M ON bcycle32M;

ALTER USER XOXOGOSSIP QUOTA 100M ON bcycle64M;

ALTER USER XOXOGOSSIP QUOTA 100M ON bcycle8192M;

ALTER USER XOXOGOSSIP QUOTA 100M ON bcycle16384M;


ALTER TABLE BC_ACCOUNT MOVE
    PCTFREE 5
    STORAGE(INITIAL 851968K NEXT 65536K)
    TABLESPACE bcycle64M;

ALTER TABLE BC_BICYCLE MOVE
    PCTFREE 0
    STORAGE(INITIAL 12416K NEXT 128K)
    TABLESPACE bcycle128K;

ALTER TABLE BC_BICYCLE_STATUS MOVE
    PCTFREE 5
    STORAGE(INITIAL 33554432K NEXT 16777216K)
    TABLESPACE BCYCLE16384M;

ALTER TABLE BC_COUNTRY MOVE
    PCTFREE 0
    STORAGE(INITIAL 0000000000 NEXT 0000000000)
    TABLESPACE 0000000000;

ALTER TABLE BC_DOCK MOVE
    PCTFREE 0
    STORAGE(INITIAL 9472K NEXT 128K)
    TABLESPACE BCYCLE128K;

ALTER TABLE BC_MEMBERSHIP MOVE
    PCTFREE 5
    STORAGE(INITIAL 524288K NEXT 32768K)
    TABLESPACE BCYCLE32M;

ALTER TABLE BC_PASS MOVE
    PCTFREE 0 STORAGE(INITIAL 384K NEXT 64K)
    TABLESPACE BCYCLE64K;

ALTER TABLE BC_PROGRAM MOVE
    PCTFREE 0
    STORAGE(INITIAL 128K NEXT 64K)
    TABLESPACE BCYCLE64K;

ALTER TABLE BC_STATION MOVE
    PCTFREE 5
    STORAGE(INITIAL 4416K NEXT 64K)
    TABLESPACE BCYCLE64K;

ALTER TABLE BC_TRIP MOVE
    PCTFREE 10
    STORAGE(INITIAL 16777216K NEXT 8388608K)
    TABLESPACE BCYCLE8192M;

------noe skal her før

CREATE ROLE read_priv IDENTIFIED BY XOXOREADONLY;
GRANT CREATE SESSION TO read_priv;
GRANT SELECT ON BC_ACCOUNT TO read_priv;
GRANT SELECT ON BC_BICYCLE TO read_priv;
GRANT SELECT ON BC_BICYCLE_STATUS TO read_priv;
GRANT SELECT ON BC_COUNTRY TO read_priv;
GRANT SELECT ON BC_DOCK TO read_priv;
GRANT SELECT ON BC_MEMBERSHIP TO read_priv;
GRANT SELECT ON BC_PASS TO read_priv;
GRANT SELECT ON BC_PROGRAM TO read_priv;
GRANT SELECT ON BC_STATION TO read_priv;
GRANT SELECT ON BC_TRIP TO read_priv;

CREATE ROLE pkgadmin IDENTIFIED BY XOXOADMIN;
GRANT CREATE SESSION TO pkgadmin;
GRANT EXECUTE ON BCYCLE3B_PKG TO pkgadmin;

CREATE ROLE pkgrequestadmin IDENTIFIED BY XOXOREQUEST;
GRANT CREATE SESSION TO pkgrequestadmin;
GRANT EXECUTE ON NUMBER_OF_BICYLES_PP TO pkgrequestadmin;
GRANT EXECUTE ON ADD_DOCK_PP TO pkgrequestadmin;
GRANT EXECUTE ON BEGIN_TRIP_PP TO pkgrequestadmin;
GRANT EXECUTE ON BICYCLE_SUMMARY_PP TO pkgrequestadmin;
GRANT EXECUTE ON CREATE_ACCOUNT_PP TO pkgrequestadmin;
GRANT EXECUTE ON CREATE_BICYCLE_PP TO pkgrequestadmin;
GRANT EXECUTE ON CREATE_STATION_PP TO pkgrequestadmin;
GRANT EXECUTE ON END_TRIP_PP TO pkgrequestadmin;
GRANT EXECUTE ON LIST_AVAILABLE_BICYCLES_PP TO pkgrequestadmin;
GRANT EXECUTE ON PURCHASE_MEMBERSHIP_PP TO pkgrequestadmin;
GRANT EXECUTE ON REMOVE_BICYCLE_PP TO pkgrequestadmin;
GRANT EXECUTE ON UPDATE_BICYCLE_STATUS_PP TO pkgrequestadmin;
GRANT EXECUTE ON UPDATE_BICYCLE_STATUS_PP TO pkgrequestadmin;
GRANT EXECUTE ON UPDATE_STATION_STATUS_PP TO pkgrequestadmin;

CREATE PROFILE GOSSIPGANG_PROFILE LIMIT
    SESSIONS_PER_USER 5
    CPU_PER_SESSION 360000
    CONNECT_TIME 180
    IDLE_TIME 5;

CREATE USER GossipMember_1
    IDENTIFIED BY GOSSIPSQUAD
    PROFILE GOSSIPGANG_PROFILE
    DEFAULT TABLESPACE USERS
    QUOTA 0M ON USERS;

CREATE USER GossipMember_2
    IDENTIFIED BY GOSSIPSQUAD
    PROFILE GOSSIPGANG_PROFILE
    DEFAULT TABLESPACE USERS
    QUOTA 250M ON USERS;

GRANT read_priv TO GossipMember_1  IDENTIFIED BY XOXOREADONLY;
GRANT pkgadmin TO GossipMember_2 IDENTIFIED BY XOXOADMIN;

SELECT * FROM USER_TABLE;
SELECT * FROM USER_INDEXES;

SELECT * FROM dba_tables
WHERE owner = 'XOXOGOSSIP' AND table_name = '';









