CREATE TABLESPACE T64
DATAFILE '/u01/app/oracle/oradata/WOLCOTTDB/T64.dbf'
SIZE 2752K autoextend on
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 64K
SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE T128
DATAFILE '/u01/app/oracle/oradata/WOLCOTTDB/T128.dbf'
SIZE 1280K autoextend on
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 128K
SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE T256
DATAFILE '/u01/app/oracle/oradata/WOLCOTTDB/T256.dbf'
SIZE 2304K autoextend on
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 256K
SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE T512
DATAFILE '/u01/app/oracle/oradata/WOLCOTTDB/T512.dbf'
SIZE 4M autoextend on
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 512K
SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE T2048
DATAFILE '/u01/app/oracle/oradata/WOLCOTTDB/T2048.dbf'
SIZE 4M autoextend on
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 2048K
SEGMENT SPACE MANAGEMENT AUTO;

ALTER USER group11 QUOTA 100M on T64;

ALTER USER group11 QUOTA 100M on T128;

ALTER USER group11 QUOTA 100M on T256;

ALTER USER group11 QUOTA 100M on T512;

ALTER USER group11 QUOTA 100M on T2048;

ALTER TABLE CP_ACCOUNT MOVE PCTFREE 25 STORAGE(INITIAL 320K NEXT 64K) TABLESPACE T64;

ALTER TABLE CP_AGENCY MOVE PCTFREE 5 STORAGE(INITIAL 64K NEXT 64K) TABLESPACE T64;

ALTER TABLE CP_CHURCH MOVE PCTFREE 10 STORAGE(INITIAL 512K NEXT 64K) TABLESPACE T64;

ALTER TABLE CP_CONTRIBUTION MOVE PCTFREE 0 STORAGE(INITIAL 576K NEXT 64K) TABLESPACE T64;

ALTER TABLE CP_COUNTY MOVE PCTFREE 0 STORAGE(INITIAL 64K NEXT 64K) TABLESPACE T64;

ALTER TABLE CP_COUNTY_AGENCY MOVE PCTFREE 0 STORAGE(INITIAL 64K NEXT 64K) TABLESPACE T64;

ALTER TABLE CP_STATE MOVE PCTFREE 0 STORAGE(INITIAL 64K NEXT 64K) TABLESPACE T64;

ALTER TABLE CP_TIER MOVE PCTFREE 0 STORAGE(INITIAL 64K NEXT 64K) TABLESPACE T64;

ALTER TABLE CP_PERSON MOVE PCTFREE 20 STORAGE(INITIAL 1024K NEXT 128K) TABLESPACE T128;

ALTER TABLE CP_CONTRIBUTION_DETAIL MOVE PCTFREE 10 STORAGE(INITIAL 1792K NEXT 256K) TABLESPACE T256;

ALTER TABLE CP_NEED MOVE PCTFREE 25 STORAGE(INITIAL 4M NEXT 512K) TABLESPACE T512;

ALTER TABLE CP_REQUEST MOVE PCTFREE 10 STORAGE(INITIAL 4M NEXT 2048K) TABLESPACE T2048;







ALTER INDEX ACCOUNT_PK REBUILD TABLESPACE INDX;

ALTER INDEX AGENCY_ACCOUNT_PK REBUILD TABLESPACE INDX;

ALTER INDEX AGENCY_PK REBUILD TABLESPACE INDX;

ALTER INDEX CHURCH_PK REBUILD TABLESPACE INDX;

ALTER INDEX CONTRIBUTION_DETAIL_PK REBUILD TABLESPACE INDX;

ALTER INDEX CONTRIBUTION_PK REBUILD TABLESPACE INDX;

ALTER INDEX COUNTY_AGENCY_PK REBUILD TABLESPACE INDX;

ALTER INDEX COUNTY_PK REBUILD TABLESPACE INDX;

ALTER INDEX NEED_PK REBUILD TABLESPACE INDX;

ALTER INDEX PERSON_PK REBUILD TABLESPACE INDX;

ALTER INDEX REQUEST_PK REBUILD TABLESPACE INDX;

ALTER INDEX STATE_PK REBUILD TABLESPACE INDX;

ALTER INDEX TIER_PK REBUILD TABLESPACE INDX;


create role read_priv identified by sheeeeeeeesh;
GRANT CREATE SESSION TO read_priv;
GRANT SELECT ON CP_ACCOUNT TO read_priv;
GRANT SELECT ON CP_AGENCY TO read_priv;
GRANT SELECT ON CP_AGENCY_ACCOUNT TO read_priv;
GRANT SELECT ON CP_CART TO read_priv;
GRANT SELECT ON CP_CHURCH TO read_priv;
GRANT SELECT ON CP_CONTRIBUTION TO read_priv;
GRANT SELECT ON CP_CONTRIBUTION_DETAIL TO read_priv; 
GRANT SELECT ON CP_COUNTY TO read_priv;
GRANT SELECT ON CP_COUNTY_AGENCY TO read_priv;
GRANT SELECT ON CP_NEED TO read_priv;
GRANT SELECT ON CP_PERSON TO read_priv;
GRANT SELECT ON CP_REQUEST TO read_priv;
GRANT SELECT ON CP_STATE TO read_priv;
GRANT SELECT ON CP_TIER TO read_priv;

create role pkgadmin identified by sheeeeeeeeeeeeeeeeeesh;
GRANT CREATE SESSION TO pkgadmin;
GRANT EXECUTE ON CAREPORTAL3B_PKG TO pkgadmin;

create role pkgrequestadmin identified by SHEEEEEEEEEEEEEEEEEEEEEESH;
GRANT CREATE SESSION TO pkgrequestadmin;
GRANT EXECUTE ON CREATE_REQUEST_SP TO pkgrequestadmin;
GRANT EXECUTE ON CREATE_NEED_SP TO pkgrequestadmin;
GRANT EXECUTE ON CREATE_CHURCH_SP TO pkgrequestadmin;
GRANT EXECUTE ON CREATE_AGENCY_SP TO pkgrequestadmin;

CREATE PROFILE Sheesh_profile LIMIT
    SESSIONS_PER_USER 5
    CPU_PER_SESSION 360000
    CONNECT_TIME 180
    IDLE_TIME 5;

CREATE USER Sheesh_1 
    IDENTIFIED BY SHEEEEEEEEEEEEEEESH
    PROFILE Sheesh_profile
    DEFAULT TABLESPACE USERS
    QUOTA 0M ON USERS;
    
CREATE USER Sheesh_2
    IDENTIFIED BY SHEEEEEEEEEEEEEEESH
    PROFILE Sheesh_profile
    DEFAULT TABLESPACE USERS
    QUOTA 200M ON USERS;
    
GRANT read_priv TO Sheesh_1 IDENTIFIED BY sheeeeeeeesh;
GRANT pkgadmin TO Sheesh_2 IDENTIFIED BY sheeeeeeeeeeeeeeeeeesh;

SELECT * FROM USER_TABLE;
SELECT * FROM USER_INDEXES;

